version: "3.0"
services:
  api:
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mysql:mysql
    environment:
      DB_HOST: mysql
      DB_USER: vegadns
      SECRET_DB_PASS: secret
      TRUSTED_IPS: 0.0.0.0/0
    depends_on:
      - mysql
  ui:
    restart: always
    build: ../VegaDNS-UI
    ports:
      - "80:80"
    links:
      - api:api
    depends_on:
      - api
    environment:
      # don't set this to api:5000 unless "api" resolves on your local machine
      # all client API requests are done from the browser!
      API_URL: ""
  client:
    restart: always
    build: ../VegaDNS-Client
    ports:
      - "5300:53"
      - "5300/udp:53/udp"
    links:
      - api:api
    depends_on:
      - api
    environment:
      API_URL: http://api:5000
  mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: vegadns
       MYSQL_DATABASE: vegadns
       MYSQL_USER: vegadns
       MYSQL_PASSWORD: secret
